# Generated by Django 3.0.3 on 2020-02-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('candy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Candy')),
            ],
        ),
    ]
