# Generated by Django 3.0.3 on 2020-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200218_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candy',
            name='cart',
        ),
        migrations.AddField(
            model_name='candy',
            name='cart',
            field=models.ManyToManyField(to='shop.Cart'),
        ),
    ]
