# Generated by Django 3.0.3 on 2020-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200218_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
